[package]
name = "oxidized-fiducial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
char-device = "0.16.3"
serialport = "4.3.0"
assert_hex = "0.4.1"
#opencv = "0.86.1"
